cross_val_args:
  n_splits: 3
  shuffle: True
  random_state: 0
model_args:
  n_estimators: 100
  max_depth: 2
  min_samples_leaf: 1
  random_state: 0
dataset_args:
  source: "https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/d546eaee765268bf2f487608c537c05e22e4b221/iris.csv"
  target_column: species
  feature_columns:
    - sepal_length
    - sepal_width
    - petal_length
    - petal_width
labels: {}
output_path: ../data/training/dev
